### ISSUE TITLE
Material Request: MToon

### ISSUE THREAD

**Issue by kazu0617** [Xlinka/NeosPlus#105]
Current NEOSPlus has debug material. https://github.com/Xlinka/NeosPlus/blob/main/Materials/TestMaterial.cs

I want to use more material for compatibility of other VR Platform like MToon in VRM.

I think just export material configuration into cs, compile it from modified unity sdk, upload to neosdb and attach into cs.

**Comment by kazu0617** [comment]
MToon: https://github.com/Santarh/MToon

**Comment by LeCloutPanda** [comment]
Materials aren't as easy as making a orb we have to make a shader that works for Neos, the test material orb is just how you change the values so the actual shader it is using is a Neos one but we are working on getting custom shaders working

**Comment by kazu0617** [comment]
I know, i think shader can build by CI/CD or handy with UnitySDK (sdk is just create variant).

**Comment by Xlinka** [comment]
neosdb:///db3df16b92e7c2ba35320345626275a32cf34162f0e3b774dd6e1a1ff7f22e1f.neoshader

Compiled and as a neosdb link if you want to try writing a material ^_^

**Comment by Xlinka** [comment]
Progress has been made :)

**Comment by LeCloutPanda** [comment]
:)
