### ISSUE TITLE
[documentation] Listing of features and where to find them

### ISSUE THREAD

**Issue by sirkitree** [Xlinka/NeosPlus#124]
The README originally had some of this information and it was removed, but there isn't another place where it talks about what all is included here nor directing people where to look for it in Neos.

If not in the README, can we put it on a Wiki page?

---
Features that have been added so far:

# Nodes
- Logix/Avatar/NearestUser
- Logix/Json/JsonAddToObject
- Logix/Json/JsonAppendToArray
- Logix/Json/JsonCountArrayChildren
- Logix/Json/JsonCountObjectChildren
- Logix/Json/JsonEmpty
- Logix/Json/JsonGetFromArray
- Logix/Json/JsonGetFromObject
- Logix/Json/JsonInfo
- Logix/Json/JsonInsertToArray
- Logix/Json/JsonParseString
- Logix/Json/JsonParseStringArray
- Logix/Json/JsonQuickGetFromObject
- Logix/Json/JsonRemoveFromArray
- Logix/Json/JsonRemoveFromObject
- Logix/Json/JsonToString
- Logix/Locomotion/IsUserInNoclip
- Logix/Math/Matrix/GaussianElimination
- Logix/Math/Matrix/GaussJordanElimination
- Logix/Math/Random/RandomBool2
- Logix/Math/Random/RandomBool3
- Logix/Math/Random/RandomBool4
- Logix/Math/Random/RandomCharacter
- Logix/Math/Random/RandomDouble
- Logix/Math/Random/RandomInt2
- Logix/Math/Random/RandomInt3
- Logix/Math/Random/RandomInt4
- Logix/Math/Random/RandomLetter
- Logix/Math/EulersToientFunction
- Logix/Math/Factorial
- Logix/Math/SortNode
- Logix/Math/MinMax
- Logix/Network/HTTPRequest
- Logix/Operators/ZeroOneI
- Logix/Operators/DoubleInput
- Logix/Playback/IsPaused
- Logix/Playback/IsStopped
- Logix/Slots/CreateEmptySlot
- Logix/Slots/GetGrandparent
- Logix/String/CountSubstring
- Logix/String/DecodeBase64
- Logix/String/EncodeBase64
- Logix/String/EndcodeMD5
- Logix/String/EncodeSha256
- Logix/String/HammingDistance
- Logix/String/HammingDistanceNonNullable
- Logix/Users/IsUserInSeatedMode

## Components
- Physics/Cloth/Cloth
- Physics/Cloth/ClothCapsuleCollider
- Physics/Cloth/ClothSphereCollider
- Add-ons/Wizards/MeshColliderManagementTools
- Utility/GrabberSimulator

## Materials
- Assets/Materials/NeosPlus/TestMaterial
---

**Comment by Xlinka** [comment]
yeah the wiki pages for components and Logix was meant to handle this but never got round to documentation. if i recall there is a another plugin for wiki documentation for wiki.neos.com i wonder if we can use that.

**Comment by sirkitree** [comment]
The wiki here is a good place because people will look through it first. I'd be hap to update it if I can have access

**Comment by Xlinka** [comment]
Access has been granted for now only use it to edit the wiki pages. We are grateful for your contribution to the project.
