### ISSUE TITLE
JSON > Add to Object only gives null value

### ISSUE THREAD

**Issue by sirkitree** [Xlinka/NeosPlus#125]
Hi, thanks so much for the JSON nodes! 

I'm finally getting around to testing them out for a project and I'm noticing that the Add To Object doesn't seem to work as I expect. I'm unsure if this is a bug or just a mistake on my part.

You can see in the provided screenshot, I'm passing in a JObject and trying to add a string and an int, both resulting in a null value.
![20230405104124_1](https://user-images.githubusercontent.com/28543/230161838-3173796f-4ea9-413b-870b-adab7d75bf37.jpg)

Perhaps a separate issue (nitpicking here) but maybe it should be called "Append To Object" to match with the "Append to Array".

**Comment by Frozenreflex** [comment]
I just pushed a commit that should fix it. The array methods are named as such because Append and Insert operations function differently, Add does not function the same as either of them.

**Comment by Xlinka** [comment]
This should be fixed now with the code on the GitHub now building it separately will allow the use until a release.
