### ISSUE TITLE
Add Additional Physics Nodes

### ISSUE THREAD

**Issue by DoubleStyx** [Xlinka/NeosPlus#13]
Create nodes for various physical calculations, such as friction, drag, refraction, etc.

**Comment by DoubleStyx** [comment]
Angular velocity, moment of inertia.

**Comment by Xlinka** [comment]
this issue says additional nodes what are the currents one base game.

**Comment by DoubleStyx** [comment]
Currently there are only two in Math>Physics: Torque Estimate and Trajectory

**Comment by Xlinka** [comment]
Thank you I'll look into this issue when I get home

**Comment by Xlinka** [comment]
also do u meant static friction or kinetic friction or would u like a enum to toggle between the two ?

**Comment by Xlinka** [comment]
does https://github.com/Xlinka/NeosPlus/pull/163 meet your needs ?

**Comment by DoubleStyx** [comment]
Yea that should be good.
