### ISSUE TITLE
Menger Sponge, Mobius Strip and Sierpinksi Pyramid in wrong location 

### ISSUE THREAD

**Issue by LeCloutPanda** [Xlinka/NeosPlus#130]
All three don't have a Comp location I could be stupid on how those classes work as I've never look at them but add a location like the rest of the procedurals do. :)

**Comment by Xlinka** [comment]
Assets > Procedural Meshes
 
![image](https://user-images.githubusercontent.com/22996716/231878185-99ee2166-1791-4645-aaa4-8b6984269fa8.png)

**Comment by sirkitree** [comment]
![2023-04-13 20 46 37](https://user-images.githubusercontent.com/28543/231879216-fb90804a-ce1a-4e51-bfbd-88ffebc6f4c3.jpg)

**Comment by Xlinka** [comment]
hmm can you see my session in the world browser right now ? if not then i belive your using a older neos+

**Comment by sirkitree** [comment]
I cannot but I downloaded from the Release notes...

**Comment by Xlinka** [comment]
double check the filesize of your  neosplus v2023.04.12 the latest is 263kb

**Comment by sirkitree** [comment]
Sorry my bad, found that Brave was blocking the download, so I thought I had it but had to dig to find that it was being blocked, there was no notice from Brave at all 🤷
