### ISSUE TITLE
MToon Shader: Expose OutlineWidthMode and OutlineColorMode

### ISSUE THREAD

**Issue by Tiny-Plume** [Xlinka/NeosPlus#139]
Currently, the outlines feature is not functional within the MToon shader. This issue is likely due to the inability to edit the OutlineWidthMode and OutlineColorMode.

It would be neat to expose these values in order to make the shader feature-complete.

![image](https://github.com/Xlinka/NeosPlus/assets/11463075/5ba9d119-78ca-4265-9923-81a9bfcf1e20)

**Comment by Xlinka** [comment]
looking into it now

**Comment by Xlinka** [comment]
fixed in #142
