### ISSUE TITLE
Parallax Occlusion Alpha

### ISSUE THREAD

**Issue by CoffeeKei** [Xlinka/NeosPlus#147]
Add alpha and cutout to parallax occlusion material for use with decals.

**Comment by Xlinka** [comment]
looking into this now.

**Comment by Xlinka** [comment]
added shader code on the github and now will be adding alpha and cutout to parralax for testing

**Comment by Xlinka** [comment]
https://github.com/Xlinka/NeosPlus/blob/main/NEOSPlus/Shaders/ParralaxAlphav1.shader

test this please in unity idk if it works. before i add it to neos+

**Comment by Xlinka** [comment]
![image](https://github.com/Xlinka/NeosPlus/assets/22996716/04e4ffa7-89b6-4463-836d-daabddfb94d3)
got it working

**Comment by Xlinka** [comment]
Will be added next update.
