### ISSUE TITLE
"CopyToPlugin" build configuration doesn't work for me

### ISSUE THREAD

**Issue by Nytra** [Xlinka/NeosPlus#151]
I would expect this config to copy the output DLL to the Neos Libraries folder but it doesn't copy anything.

**Comment by Xlinka** [comment]
ill look into it now since the source generators are not working either since some point.

**Comment by Xlinka** [comment]
<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'CopyToPlugin|AnyCPU'">
  <PostBuildEvent>echo Copying "$(TargetPath)" to "$(NeosPath)\Libraries"</PostBuildEvent>
</PropertyGroup>


added a echo to it so we can debug it so if u run it now it should tell you where its putting it and we can figure out the solution.

**Comment by Nytra** [comment]
Just tested this and it doesn't seem to echo anything, which maybe means that this event isn't being triggered? My build config is CopyToPlugin with AnyCPU.

**Comment by Frozenreflex** [comment]
As far as I can tell, it never worked. If I recall correctly, someone added it to the base configuration and it made compiling impossible because it would always throw an error, so it was moved to it's own configuration. I vouch for completely removing it.
