### ISSUE TITLE
Porting some Neos mods like ikculling and photonic freedom

### ISSUE THREAD

**Issue by alexderpyfox** [Xlinka/NeosPlus#22]
Not sure if this is a good idea but since this will be for features people want and to essential not use mods or since using this with NML is kinda bad porting some mods to this might be handy

**Comment by DoubleStyx** [comment]
We can't really do this since most of those mods require some degree of patching.

**Comment by Xlinka** [comment]
Neos Has No Plan to add patching methods within the plugin to patch the main game.
