### ISSUE TITLE
Two JSON parse nodes.

### ISSUE THREAD

**Issue by reality-exe** [Xlinka/NeosPlus#24]
Get JSON data from a specific integer (Like Multiplex) and amount of objects / data

```json
{
    {   0
        "TestData":"123456"
    },
    {   1
        "TestData":"321654"
    },
    {   2
        "TestData":"321654"
    }
}
```
And amount would count to 3.

**Comment by Frozenreflex** [comment]
I've created a node for counting the immediate children of a JObject, but I don't know how to interpret your first request, are you asking for array support? The Json you provided also doesn't seem to be valid.

**Comment by reality-exe** [comment]
> I don't know how to interpret your first request, are you asking for array support?

Being able to select a specific data table from multiple like multiplexers. The JSON i provided was just a quick show to say sort of what i was talking about. 
Grabbing the data from `0` would return just the data in the first object so it would be `"TestData":"123456"` however if i grab data from 1 it would return `"TestData":"321654"`.
Hopefully i cleared that up i am tired while making this lol

**Comment by reality-exe** [comment]
Oh so yeah i guess it would be array support nevermind

**Comment by Frozenreflex** [comment]
> Oh so yeah i guess it would be array support nevermind

Taking your JSON sample, removing the numbers, and replacing the first pair of brackets with square brackets does make it a valid array. I am working on array support.

**Comment by reality-exe** [comment]
Yeah I'm a little slow rn sorry about that

**Comment by Frozenreflex** [comment]
Added
