### ISSUE TITLE
Two Add Component nodes

### ISSUE THREAD

**Issue by reality-exe** [Xlinka/NeosPlus#25]
Two `Add Component` nodes.
![image](https://user-images.githubusercontent.com/95439036/184791094-257fe8ac-7838-443a-b5f0-82572f60ae3c.png)

Left (Presumably the wrong node):
![image](https://user-images.githubusercontent.com/95439036/184791127-570a36b6-120c-4a2d-bc6e-6bf8c36433ce.png)

Right:
![image](https://user-images.githubusercontent.com/95439036/184791195-4b452809-864f-4996-8f75-855671d84c9b.png)

**Comment by Frozenreflex** [comment]
These nodes have been entirely removed.

**Comment by Xlinka** [comment]
This was recently removed all the array stuff and the component stuff and will be reworked.

**Comment by reality-exe** [comment]
alright
