### ISSUE TITLE
Put NML in Neos+

### ISSUE THREAD

**Issue by alexderpyfox** [Xlinka/NeosPlus#26]
So it is one less compatibility to worry about because then if you use mods with Neos+ you only need Neos+ and no need to spoof compatibility hash when using Neos+ with mods since then neos+ would incl the thing to load mods and then it would be just Neos+ incl NML and then show up as using Neos+.DLL since then you only need Neos+ but I'm not talking about it combining both permanently but only adding it to here so it is incl and ofc you then don't spoof the hash since Neos+ being a seperate hash is good so you don't accidentally join people that don't have it but at the same time can use all the mods that you use on NML so then i would launch Neos+ if i wanted to play Neos+ with mods and just launch NML if i play regular Neos with mods so Neos+ would still show up but as only requirement as needing the Neos+ to join

**Comment by zkxs** [comment]
Wow that's a wall of text.

This is more of a NML problem than a Neos+ problem. I've created an issue: https://github.com/neos-modding-group/NeosModLoader/issues/58
