### ISSUE TITLE
New Node & HTTP Request headers

### ISSUE THREAD

**Issue by reality-exe** [Xlinka/NeosPlus#39]
A nearest user node so we dont have to use Get Nearest User Head.
![image](https://user-images.githubusercontent.com/95439036/186213578-cee9422c-6fc2-4a1b-9fb5-b77dd5603494.png)

Add headers to HTTP requests as we can't do any sort of authorization with API's such as GitHub
![image](https://user-images.githubusercontent.com/95439036/186214644-aea111ce-cceb-4d83-8afa-27ad370e0a62.png)

**Comment by LeCloutPanda** [comment]
I'll look into it :)

**Comment by Xlinka** [comment]
added recently by @Lexevolution  will be in Tuesday release
