### ISSUE TITLE
Bepu - Cloth Physics

### ISSUE THREAD

**Issue by Elektrospy** [Xlinka/NeosPlus#51]
- cloth physics
    - Froox said to not use the bepu "native" cloth simulation
        - seems to be based around "one sphere collider per vertex", which can get expensive really fast
    - may needs another approach with similar results

- Neos issues:
  - https://github.com/Neos-Metaverse/NeosPublic/issues/2853

**Comment by dfgHiatus** [comment]
Currently working on this: https://github.com/Xlinka/NeosPlus/pull/64

As it stands, this supports procedural meshes only. This is an implementation of Unity's Cloth component

**Comment by DoubleStyx** [comment]
Support for bepu cloth physics is a good long-term goal, especially if Froox has plans to remove Unity from Neos in the future.
