### ISSUE TITLE
Fix the duplicate interface problem 

### ISSUE THREAD

**Issue by epicEaston197** [Xlinka/NeosPlus#74]
this has been a problem that has been plaguing NEOS since Logix was created I don't think I'm the only one that finds duplicate interfaces really annoying and irritating

**Comment by DoubleStyx** [comment]
This is a bug regarding how interface cards are generated. Fixing this would likely require patching.

**Comment by Frozenreflex** [comment]
Requires patches, which are not in the scope of this plugin.
