### ISSUE TITLE
Nearest User Node breaks Pull Request guidelines.

### ISSUE THREAD

**Issue by art0007i** [Xlinka/NeosPlus#89]
in the guidelines it says `Code submissions must not duplicate existing functionality within NeosVR or the NeosPlus plugin`
but that node is literally just copy pasted nearest user head but without the slot output.

**Comment by DoubleStyx** [comment]
It might be better to have an enum for the node that allows a specific bone or tracking point to be selected.

**Comment by ProbablePrime** [comment]
Use the body node enum.

**Comment by dfgHiatus** [comment]
Removed in [v2022.09.06](https://github.com/Xlinka/NeosPlus/releases/tag/v2022.09.06)
